<template>
  <v-app-bar>
    <v-container>
      <h1>Back</h1>
    </v-container>
  </v-app-bar>
  <v-main>
    <v-container>
      <router-view></router-view>
    </v-container>
  </v-main>
</template>